version: '3.8'

services:
  database: 
    image: postgres
    container_name: app-dws-database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app-dws
    volumes:
      - pgdata:/data/postgres

  # app:
  #   build: .
  #   container_name: app-dws
  #   restart: always
  #   ports: 
  #     - 3333:3333
  #     - 9229:9229
  #   volumes: 
  #     - .:/usr/app
  #   links: 
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local
