version: '3.8'


services:
  database:
    image: postgres
    container_name: db-app-dws
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app-dws
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: api-app-dws
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    environment:
      - DATABASE_USER=user
      - DATABASE_PASS=pass
      - DATABASE_HOST=db-app-dws
      - DATABASE_PORT=5432
      - DATABASE_NAME=app-dws
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
